# Assignments 3 Numpy

## Reference 
[Numpy assignment](https://gist.github.com/ShibaniOtis/666ebd044d591793f1328f90d6359e79)


In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Create a 2D Numpy Array

In [6]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]

# Convert list to Numpy Array
# Every element is the same type
A = np.array(a)

'''
print(A)
[[11 12 13]
 [21 22 23]
 [31 32 33]]
'''

# Show the numpy array dimensions
A.ndim

'''
print(A.ndim)
2
'''

# Show the numpy array shape
A.shape
'''
print(A.shape)
(3,3)
'''

(3, 3)
